name: Build

on:
  push:
    tags:
      - "v*"

jobs:
  docker:
    if: github.repository_owner == 'sinzlab'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker setup-buildx-action
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get tag
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            sinzlab/pytorch:${{ env.TAG }}
            sinzlab/pytorch:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
